header:
  version: 15

repos:
  poky:
    url: https://git.yoctoproject.org/git/poky
    branch: kirkstone
    path: layers/poky
    layers:
      meta:
      meta-poky:

  meta-openembedded:
    url: http://git.openembedded.org/meta-openembedded
    branch: kirkstone
    path: layers/meta-openembedded
    layers:
      meta-oe:
      meta-python:
      meta-multimedia:
      meta-webserver:
      meta-networking:
